name: Frontend E2E tests
on:
  push:
    branches: [ main, master ]
    paths:
      - 'apps/frontend/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'apps/frontend/**'
jobs:
  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./tooling/github/setup
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: turbo test:e2e -F frontend
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: apps/frontend/playwright-report
        retention-days: 30
